### ISSUE TITLE
Combining marks break joining behaviour

### ISSUE THREAD

**Issue by babelstone** [notofonts/old-uyghur#2]
Testing on Google Chrome Version 115.0.5790.110 with Noto Serif Old Uyghur (NotoSerifOldUyghur-Regular.ttf) v. 1.002.

The list of attested sequences with combining marks listed in [L2/20-191](https://www.unicode.org/L2/L2020/20191-old-uyghur.pdf) Section 8.2 are all rendered within a word using the isolate form of the base letter, and so do not join with any preceding or following letter. Note that all sequences of letter plus combining mark that are not explicitly listed in Section 8.2 are rendered with the expected positional form or the base letter, and the combining mark is simply overlaid without any special positioning (which is acceptable behaviour for unattested sequences).

See attached image showing examples of each attested sequence of letter plus combining mark in initial, medial, and final position in a word. In all cases the base letter is incorrectly rendered using the isolate form.

![combining-marks](https://github.com/notofonts/old-uyghur/assets/20558386/0022b3ab-f49b-45a8-b7aa-a5ff833403aa)

1. Steps to reproduce
Render a word which includes any of the sequence of letter plus combining listed in L2/20-191 Section 8.2, e.g. "𐾀𐽶𐽿𐾅𐽸𐽰𐽺𐾀𐽶" (tišdanti) with shin + double dot below.

2. Observed results
The combining mark is correctly positioned with respect to the base letter, but the base letter takes the isolate form and is not joined to the preceding or following letter.

3. Expected results
The combining mark should be correctly positioned with respect to the base letter, and the base letter should take the appropriate initial, medial, or final form depending on its position in the word,

  4. Additional information 
Reference:  [L2/20-191](https://www.unicode.org/L2/L2020/20191-old-uyghur.pdf) Section 8.2

**Comment by simoncozens** [comment]
I have a feeling that the correct way of fixing this (and the other joining-related issues) is to use the USE's positional form handling rather than (as we do at the moment) try to do joining ourselves using contextual substitutions.

**Comment by babelstone** [comment]
I suspect that it is a problem with the order that the features are applied: the font uses ccmp to apply a combining mark to the basic and positional forms of a letter, but as ccmp is always applied before any other feature (presumably including init, medi, and fina), only the basic substitution is applied, and the substitutions of the positional forms never occur. I did a quick test where I simply changed the ccmp feature to liga, and the forms with combining marks are all displayed correctly, as shown in this image:
![combining-marks-liga](https://github.com/notofonts/old-uyghur/assets/20558386/c6d83781-1e68-44a7-aafc-e82b062de82e)

**Comment by simoncozens** [comment]
I'm not entirely sure why we have these precomposed forms. I wonder if the designer is allergic to mark positioning. I'm just going to completely disable the lookup and see if that's better.
