### ISSUE TITLE
Letters after kaph and pe try to join them on the baseline

### ISSUE THREAD

**Issue by dscorbett** [notofonts/old-uyghur#6]
### Font
NotoSerifOldUyghur-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/old-uyghur/releases/tag/NotoSerifOldUyghur-v1.003
Date: 2023-09-29

### Font version
Version 1.003

### Issue
Kaph and pe connect to the following letter via a swash under the baseline, so the following letter should not try to connect to it on the baseline. If the following letter is in medial position it should use its initial glyph, and if the following letter is in final position it should use its isolated glyph. 'rlig' already handles a few combinations but most are missing.

There should probably also be some adjustment before final gimel-heth to avoid overlapping its descender. Other letters might need more space too.

Mem might be an exception because its final and isolated glyphs look very different, unlike all other letters. Either way, the current behavior is wrong: mem should not use a glyph with a rightwards connecting baseline stroke with a square-cut terminal when there is nothing in the previous glyph for it to connect to.

### Character data
<span dir="ltr">𐽱𐽷𐽰</span>
U+10F71 OLD UYGHUR LETTER BETH
U+10F77 OLD UYGHUR LETTER KAPH
U+10F70 OLD UYGHUR LETTER ALEPH

<span dir="ltr">𐽼𐽰𐽴</span>
U+10F7C OLD UYGHUR LETTER PE
U+10F70 OLD UYGHUR LETTER ALEPH
U+10F74 OLD UYGHUR LETTER ZAYIN

<span dir="ltr">𐽷𐽲</span>
U+10F77 OLD UYGHUR LETTER KAPH
U+10F72 OLD UYGHUR LETTER GIMEL-HETH

<span dir="ltr">𐽼𐽲</span>
U+10F7C OLD UYGHUR LETTER PE
U+10F72 OLD UYGHUR LETTER GIMEL-HETH

<span dir="ltr">𐽼𐽹</span>
U+10F7C OLD UYGHUR LETTER PE
U+10F79 OLD UYGHUR LETTER MEM

### Screenshots
![𐽱𐽷𐽰](https://github.com/notofonts/old-uyghur/assets/1124347/aa942e30-3463-4625-94a2-dccb88e8cc34)
![𐽼𐽰𐽴](https://github.com/notofonts/old-uyghur/assets/1124347/02cf1833-0b0c-440c-b7d6-9d992be80f4c)
![𐽷𐽲](https://github.com/notofonts/old-uyghur/assets/1124347/4dde063f-95c6-45c5-b9d5-4eb080ad7553)
![𐽼𐽲](https://github.com/notofonts/old-uyghur/assets/1124347/bce7e0bf-4f18-4f73-8846-7414c27332ea)
![𐽼𐽹](https://github.com/notofonts/old-uyghur/assets/1124347/5724db21-cbb1-47ca-99d0-9f3316aafd2b)

**Comment by simoncozens** [comment]
I believe I've now fixed this. We now have:

![shape](https://github.com/notofonts/old-uyghur/assets/106728/3d80fe43-be4f-4329-86fa-069f163c8920)

With similar adjustments to shin and samekh.
